---
title: "Stats 572 - Simulation Study Comparison"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Libr.
```{r}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

## Functions
```{r}
source(paste0(dir,"Code/functions/AIZResults.R"))
source(paste0(dir,"Code/functions/MonteCarloResults.R"))
source(paste0(dir,"Code/functions/SimulationReformatResultsFunction.R"))
```

## Results
```{r}
### Set Up ###
AIZ = AIZResults(type = "Linear")
SimulationResultsList = readRDS(file = paste0(dir,"data/SimulationCases/Linear/SimulationResults.rds"))
SimulationResultsReformatted = SimulationReformatResultsFunction(SimulationResultsList)
SimSEMedianList = SimulationResultsReformatted$SimSEMedianList 
MonteCarloREsults = MonteCarloResults(SimulationResultsReformatted, 5)
RunTimeList = SimulationResultsReformatted$RunTimeList
CoverageList = data.frame(SimulationResultsReformatted$CoverageList)
ParameterVector = SimulationResultsReformatted$ParameterVector
```

# Comparison
## Discrepancy 
```{r}
### Discrepancy Epsilon ###
depsilon = .1

### Discrepancy ###
Discrepancy = list()
Discrepancy$SEPop = as.matrix(abs(AIZ$MedianSEPop - SimSEMedianList$Population))
Discrepancy$SECond = as.matrix(abs(AIZ$MedianSECond - SimSEMedianList$Conditional))
Discrepancy$CoverageCondPop = as.matrix(abs(AIZ$ThetaCondVarPop - CoverageList[,3]))
Discrepancy$CoverageCondCond = as.matrix(abs(AIZ$ThetaCondVarCond - CoverageList[,4]))
Discrepancy$Difference = as.matrix(abs(AIZ$Difference - SimSEMedianList$Difference))

### Indices ###
LargeDiscrepancyIndices = list()
LargeDiscrepancyIndices$SEPop = which(Discrepancy$SEPop >= depsilon)
LargeDiscrepancyIndices$SECond = which(Discrepancy$SECond >= depsilon)
LargeDiscrepancyIndices$CoverageCondPop = which(Discrepancy$CoverageCondPop >= depsilon)
LargeDiscrepancyIndices$CoverageCondCond = which(Discrepancy$CoverageCondCond >= depsilon)
LargeDiscrepancyIndices$Difference = which(Discrepancy$Difference >= depsilon)

LargeDiscrepancyIndices
```
## Average Discrepancies
```{r}
mean(Discrepancy$Difference)
mean(Discrepancy$SEPop)
mean(Discrepancy$SECond)
mean(Discrepancy$CoverageCondPop)
mean(Discrepancy$CoverageCondCond)
```
# xtable


```{r}
### AIZ Coverage and SE Table ###
# cbind(SimSEMedianList[,c(1:5)],CoverageList,SimSEMedianList[,c(6,7,8)]) %>%
# xtable(digits = 5,
#        caption = "Simulation Results (Linear Model)")

# ### Monte Carlo Results ###
# MonteCarloREsults$MonteCarliResults_Population %>%
#   xtable(digits = 5,
#          caption = "Monte Carlo Simulation $\theta_{Cond}$ Results (Linear Model)")
# 
# MonteCarloREsults$MonteCarliResults_Conditional %>%
#   xtable(digits = 5,
#          caption = "Monte Carlo Simulation $\theta_{Pop}$ Results (Linear Model)")
```

# Monte Carlo Results
```{r}

```

