---
title: "Stats 572 - Simulation Study Comparison"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Libr.
```{r}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
```

## Rm. Var.
```{r}
# rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

## Functions
```{r}
source(paste0(dir,"Code/functions/AIZResults.R"))
source(paste0(dir,"Code/functions/SimulationReformatResultsFunction.R"))
```

## Results
```{r}
### Set Up ###
AIZ = AIZResults(Binary = FALSE)
SimulationResultsList = readRDS(file = paste0(dir,"data/SimulationCases/Linear/SimulationResults.rds"))
SimulationResultsReformatted = SimulationReformatResultsFunction(SimulationResultsList)
SimSEMedianList = SimulationResultsReformatted$SimSEMedianList
RunTimeList = SimulationResultsReformatted$RunTimeList
CoverageList = data.frame(SimulationResultsReformatted$CoverageList)
ParameterVector = SimulationResultsReformatted$ParameterVector
```

# Comparison

## Discrepancy 
```{r}
### Discrepancy Epsilon ###
depsilon = .1

### Discrepancy ###
Discrepancy = list()
Discrepancy$SEPop = as.matrix(abs(AIZ$MedianSEPop - 2*SimSEMedianList$Population))
Discrepancy$SECond = as.matrix(abs(AIZ$MedianSECond - 2*SimSEMedianList$Conditional))
Discrepancy$CoverageCondPop = as.matrix(abs(AIZ$ThetaCondVarPop - CoverageList[,3]))
Discrepancy$CoverageCondCond = as.matrix(abs(AIZ$ThetaCondVarCond - CoverageList[,4]))
Discrepancy$Difference = as.matrix(abs(AIZ$Difference - SimSEMedianList$Difference))

### Indices ###
LargeDiscrepancyIndices = list()
LargeDiscrepancyIndices$SEPop = which(Discrepancy$SEPop >=depsilon)
LargeDiscrepancyIndices$SECond = which(Discrepancy$SECond >=depsilon)
LargeDiscrepancyIndices$CoverageCondPop = which(Discrepancy$CoverageCondPop >=depsilon)
LargeDiscrepancyIndices$CoverageCondCond = which(Discrepancy$CoverageCondCond >=depsilon)
LargeDiscrepancyIndices$Difference = which(Discrepancy$Difference >=depsilon)

LargeDiscrepancyIndices
```
## Average Discrepancies
```{r}
mean(Discrepancy$SEPop)
mean(Discrepancy$SECond)
mean(Discrepancy$CoverageCondPop)
mean(Discrepancy$CoverageCondCond)
```
## Difference Ranking
### Conditional
```{r}
### Set Up ###
ConditionalDiscrepancyStratifiedMatrix = matrix(ncol = 16, nrow =  10)
rownames(ConditionalDiscrepancyStratifiedMatrix) = c("Misspec_No",
                                          "Misspec_Yes",
                                          "Homo_No",
                                          "Homo_Yes",
                                          "SS_50",
                                          "SS_200",
                                          "Leverage_No",
                                          "Leverage_Yes",
                                          "K_1",
                                          "K_5")

# Misspecification #
ConditionalDiscrepancyStratifiedMatrix[1,] = Discrepancy$SECond[ which(ParameterVector$Misspec. == "No")]
ConditionalDiscrepancyStratifiedMatrix[2,] = Discrepancy$SECond[which(ParameterVector$Misspec. == "Yes")]

# Homoskedasticity #
ConditionalDiscrepancyStratifiedMatrix[3,] = Discrepancy$SECond[ which(ParameterVector$Homo. == "No")]
ConditionalDiscrepancyStratifiedMatrix[4,] = Discrepancy$SECond[ which(ParameterVector$Homo. == "Yes")]

# Misspecification #
ConditionalDiscrepancyStratifiedMatrix[5,] = Discrepancy$SECond[ which(ParameterVector$SS == 50)]
ConditionalDiscrepancyStratifiedMatrix[6,] = Discrepancy$SECond[ which(ParameterVector$SS == 200)]

# Leverage #
ConditionalDiscrepancyStratifiedMatrix[7,] = Discrepancy$SECond[ which(ParameterVector$Leverage == "No")]
ConditionalDiscrepancyStratifiedMatrix[8,] = Discrepancy$SECond[ which(ParameterVector$Leverage == "Yes")]

# Covariates #
ConditionalDiscrepancyStratifiedMatrix[9,] = Discrepancy$SECond[ which(ParameterVector$K == 1)]
ConditionalDiscrepancyStratifiedMatrix[10,] = Discrepancy$SECond[ which(ParameterVector$K == 5)]
```

### Population
```{r}
### Set Up ###
PopulationDiscrepancyStratifiedMatrix = matrix(ncol = 16, nrow =  10)
rownames(PopulationDiscrepancyStratifiedMatrix) = c("Misspec_No",
                                          "Misspec_Yes",
                                          "Homo_No",
                                          "Homo_Yes",
                                          "SS_50",
                                          "SS_200",
                                          "Leverage_No",
                                          "Leverage_Yes",
                                          "K_1",
                                          "K_5")

# Misspecification #
PopulationDiscrepancyStratifiedMatrix[1,] = Discrepancy$SEPop[ which(ParameterVector$Misspec. == "No")]
PopulationDiscrepancyStratifiedMatrix[2,] = Discrepancy$SEPop[which(ParameterVector$Misspec. == "Yes")]

# Homoskedasticity #
PopulationDiscrepancyStratifiedMatrix[3,] = Discrepancy$SEPop[ which(ParameterVector$Homo. == "No")]
PopulationDiscrepancyStratifiedMatrix[4,] = Discrepancy$SEPop[ which(ParameterVector$Homo. == "Yes")]

# Misspecification #
PopulationDiscrepancyStratifiedMatrix[5,] = Discrepancy$SEPop[ which(ParameterVector$SS == 50)]
PopulationDiscrepancyStratifiedMatrix[6,] = Discrepancy$SEPop[ which(ParameterVector$SS == 200)]

# Leverage #
PopulationDiscrepancyStratifiedMatrix[7,] = Discrepancy$SEPop[ which(ParameterVector$Leverage == "No")]
PopulationDiscrepancyStratifiedMatrix[8,] = Discrepancy$SEPop[ which(ParameterVector$Leverage == "Yes")]

# Covariates #
PopulationDiscrepancyStratifiedMatrix[9,] = Discrepancy$SEPop[ which(ParameterVector$K == 1)]
PopulationDiscrepancyStratifiedMatrix[10,] = Discrepancy$SEPop[ which(ParameterVector$K == 5)]
```

