---
title: "Stats 572 - Run Simulation Study 1"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up
## Notes
- Did I do the Mahlahnobis distance correctly

## Libr.
```{r}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

# Functions
```{r}
source(paste0(dir,"Code/functions/AIZResults.R"))
source(paste0(dir,"Code/functions/ConfidenceIntervalFunction.R"))
source(paste0(dir,"Code/functions/OneIterationFunction.R"))
source(paste0(dir,"Code/functions/SimData.R"))
source(paste0(dir,"Code/functions/SimulationFunction.R"))
source(paste0(dir,"Code/functions/SimulationReformatResultsFunction.R"))
source(paste0(dir,"Code/functions/ThetaCondFunction.R"))
source(paste0(dir,"Code/functions/VHatCondFunction.R"))
source(paste0(dir,"Code/functions/VHatCondFunctionLoop.R"))
source(paste0(dir,"Code/functions/VHatPopFunction.R"))
source(paste0(dir,"Code/functions/VHatPopFunctionLoop.R"))
source(paste0(dir,"Code/functions/WhichMinFunction.R"))
```

# Simulation
```{r}
### Set Up ###
set.seed(420)
BadParameterVector = cbind(MisspecVec = c(rep(0,16),rep(1,16)),
                        HomoskedVec = rep(c(rep(0,8), rep(0.5,8)),2),
                        SizeVec = rep(c(rep(50,4), rep(200,4)),4),
                        LeverageVec = rep(c(0,0,0.1,0.1),8),
                        KVec = rep(c(1,5),16)
                        ) %>% data.frame

### Set Up ###
set.seed(420)
ParameterVector = cbind(MisspecVec = c(rep(0,16),rep(0.1,16)),                       # Delta: Misspecification Rate
                        HomoskedVec = rep(c(rep(0,8), rep(0.5,8)),2),                # Gamma: Heteroskedasticity Rate
                        SizeVec = rep(c(rep(50,4), rep(200,4)),4),                   # N: Observations
                        LeverageVec = rep(c(0,0,0.1,0.1),8),                         # rho: Mixture Leverage
                        KVec = rep(c(1,5),16)                                        # K: Parameters
                        ) %>% data.frame
```

```{r}
### Sun Simulation ###
NSim = 50000
SimulationResultsList = list(length = nrow(ParameterVector))
for(i in 1:nrow(ParameterVector)){
  print(paste0("Case ",i))
SimulationResultsList[[i]] = SimulationFunction(NSim = NSim, ParameterVector,i, Binary = TRUE)
  write.csv(SimulationResultsList[[i]]$SimulationResults, file = paste0(dir, "data/SimulationCases/Logistic/Case",i,".csv"))

}
names(SimulationResultsList) = paste0("Case",1:nrow(ParameterVector))
saveRDS(SimulationResultsList, file = paste0(dir,"data/SimulationCases/Logistic/SimulationResults.rds"))
```