---
title: "Stats 572 - Simulation Study Comparison"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Libr.
```{r message=FALSE, warning=FALSE}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
library(ggplot2)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

## Functions
```{r}
source(paste0(dir,"Code/AIZResults.R"))
source(paste0(dir,"Code/DiscrepancyFunction.R"))
source(paste0(dir,"Code/MonteCarloResults.R"))
source(paste0(dir,"Code/SimulationReformatResultsFunction.R"))
```

## Results
### Small Sample
```{r}
### Get Files ###
file_list = list.files(path =  paste0(dir,"Results/Linear/N50_200"),
                        pattern = "\\.rds$",
                        full.names = TRUE)
SmallSampleSimulation = list()
SmallSampleSimulation = lapply(file_list, readRDS)
rm(file_list)

### Results ###
SmallSampleSimulation = SimulationReformatResultsFunction(SmallSampleSimulation)
SmallSampleSEMedianList = SmallSampleSimulation$SimSEMedianList
SmallSampleMonteCarloResults = MonteCarloResults(SmallSampleSimulation, 5)
SmallSampleRunTimeList = SmallSampleSimulation$RunTimeList  # in seconds
SmallSampleCoverageList = data.frame(SmallSampleSimulation$CoverageList) 
SmallSampleParameterVector = SmallSampleSimulation$ParameterVector

SmallSampleResultsTable = cbind(SmallSampleSEMedianList[,c(1:5)],
                                SmallSampleCoverageList[,6:9],
                                SmallSampleSEMedianList[,6:10])
rownames(SmallSampleResultsTable) = paste0("Case ", 1:nrow(SmallSampleResultsTable)) 

SmallSampleResultsTable = SmallSampleResultsTable %>% mutate(Misspec. = case_when(Misspec. == 0 ~ "No",
                                                                  Misspec. == 1 ~ "Yes"),
                                             Homo. = case_when(Homo. == 0 ~ "Yes",
                                                               Homo. == 0.5 ~ "No"),
                                             Leverage = case_when(Leverage == 0 ~ "No",
                                                                  Leverage == 0.1 ~ "Yes"))
```

### Large Sample
```{r}
### Get Files ###
file_list = list.files(path =  paste0(dir,"Results/Linear/ALL"),
                        pattern = "\\.rds$",
                        full.names = TRUE)
LargeSampleSimulation = list()
LargeSampleSimulation = lapply(file_list, readRDS)
rm(file_list)

### Results ###
LargeSampleSimulation = SimulationReformatResultsFunction(LargeSampleSimulation)
LargeSampleSEMedianList = LargeSampleSimulation$SimSEMedianList
LargeSampleMonteCarloResults = MonteCarloResults(LargeSampleSimulation, 5)
LargeSampleRunTimeList = LargeSampleSimulation$RunTimeList  # in seconds
LargeSampleCoverageList = data.frame(LargeSampleSimulation$CoverageList)
LargeSampleParameterVector = LargeSampleSimulation$ParameterVector

LargeSampleResultsTable = cbind(LargeSampleSEMedianList[,c(1:5)],
                                LargeSampleCoverageList[,6:9],
                                LargeSampleSEMedianList[,6:10])
rownames(LargeSampleResultsTable) = paste0("Case ", 1:nrow(LargeSampleResultsTable))

LargeSampleResultsTable = LargeSampleResultsTable %>% mutate(Misspec. = case_when(Misspec. == 0 ~ "No",
                                                                  Misspec. == 1 ~ "Yes"),
                                             Homo. = case_when(Homo. == 0 ~ "Yes",
                                                               Homo. == 0.5 ~ "No"),
                                             Leverage = case_when(Leverage == 0 ~ "No",
                                                                  Leverage == 0.1 ~ "Yes"))
```

# Percentage Change by N
## Set Up
```{r}
### Pivoting ###
SmallSampleSEMedianList %>% 
  select(-c(Population, Conditional, Indicator, Difference)) %>%
  pivot_wider(names_from = SS,
              values_from = PercentChange) %>%
  rename(N.50 = "50",
         N.200 = "200") %>%
  relocate(N.50, .before=N.200) %>% 
  data.frame -> PivotWiderSmallSampleSE

LargeSampleSEMedianList %>% 
  select(-c(Population, Conditional, Indicator, Difference)) %>%
  pivot_wider(names_from = SS,
              values_from = PercentChange) %>%
  rename(N.50 = "50",
         N.200 = "200",
         N.350 = "350",
         N.500 = "500",
         N.650 = "650",
         N.800 = "800",
         N.950 = "950",
         N.1100 = "1100",
         N.1250 = "1250",
         N.1400 = "1400",
         N.1550 = "1550",
         N.1700 = "1700",
         N.1850 = "1850",
         N.2000 = "2000"
         ) %>%
  mutate(ID = 1:16) %>%
  relocate(ID, .before = "Misspec.") %>%
  data.frame -> PivotWiderLargeSampleSE

PivotWiderLargeSampleSE = PivotWiderLargeSampleSE %>%
  mutate(Misspec. = case_when(Misspec. == 0 ~ "No",
                              Misspec. == 1 ~ "Yes"),
         Homo. = case_when(Homo. == 0 ~ "Yes",
                           Homo. == 0.5 ~ "No"),
         Leverage = case_when(Leverage == 0 ~ "No",
                              Leverage == 0.1 ~ "Yes"))


### xtable ###
PivotWiderLargeSampleSE %>% 
  select(-c(ID)) %>% 
  xtable(digits = 5, 
         caption = "Percent change in using conditional standard error estimates instead of population standard error estimates by sample size.", 
         include.rownames=FALSE)
```

## Plot
```{r}
### Pivot back to long format lol
LargeSampleBackToLong <- pivot_longer(PivotWiderLargeSampleSE, 
                                      cols = starts_with("N."), 
                                      names_to = "N_value", 
                                      values_to = "value") %>%
  rename(Misspecification = Misspec.,
         Heterogeneity = Homo.,
         "High Leverage" = Leverage) %>%
  mutate(Heterogeneity = case_when(Heterogeneity == "Yes" ~ "No",
                                   Heterogeneity == "No" ~ "Yes"))

### Last Observation Label ###
LastObservation <- LargeSampleBackToLong %>%
  group_by(ID) %>%
  filter(N_value == "N.2000")
  
options(repr.plot.width=30, repr.plot.height=5)

LargeSampleBackToLong %>% filter(Misspecification == "No") %>%
ggplot() +
  
  ### Line ###
  geom_line( mapping = aes(x =as.numeric(gsub("N\\.", "", N_value)), 
                          y = 100*value, 
                          group = ID, 
                          color = Misspecification,
                          linetype = `High Leverage`),
             size = 1) +
  ### Point ###
  geom_point(data = LastObservation %>% filter(Misspecification == "No"),
             mapping = aes(x =as.numeric(gsub("N\\.", "", N_value)),
                           y = 100*value,
                           shape = Heterogeneity,
                           color = Misspecification),  # Add shape aesthetic
             size = 3)  +

  ### Labels ###
    xlab("Sample Size") + 
    ylab("Percent Change (%)") + 
    scale_y_continuous(breaks = seq(-10, 0, by = 2)) +
    scale_x_continuous(breaks = seq(50, 2000, by = 150)) +
    ggtitle("Standard error reduction when using the conditional standard error estimate") +
    theme(plot.title =  element_text(size = 15, hjust = 0.5)) +
  theme_light()-> PercentChangeSSPlot
```



# Presentation Xtable
## Small Sample

### Coverage
```{r}
### Correctly Specified Models ###
# SmallSampleResultsTable %>% 
#   select(-c(Population, Conditional, Difference, Indicator, PercentChange)) %>% 
#   filter(Misspec. == "No") %>%
#   xtable(digits = 5,
#          caption = "Simulation coverage rates for 50,000 replications with small samples (correctly specified models)")

### Misspecified Models ###
# SmallSampleResultsTable %>%
#   select(-c(Population, Conditional, Difference, Indicator, PercentChange)) %>%
#   filter(Misspec. == "Yes") %>%
#   xtable(digits = 5,
#          caption = "Simulation coverage rates for 50,000 replications with small samples (misspecified models)")
```
### Percentage Change
```{r}
### Correctly Specified Models ###
# SmallSampleResultsTable %>%
#   select(-c(ThetaPop_VPop, ThetaPop_VCond, ThetaCond_VPop, ThetaCond_VCond, Difference, Indicator)) %>%
#   mutate(PercentChange = 100*PercentChange) %>%
#     filter(Misspec. == "No") %>%
#   xtable(digits = 5,
#          caption = "Simulation results over $50,000$ replications with small samples (correctly specified models)")

### Misspecified Models ###
# SmallSampleResultsTable %>%
#   select(-c(ThetaPop_VPop, ThetaPop_VCond, ThetaCond_VPop, ThetaCond_VCond, Difference, Indicator)) %>%
#   mutate(PercentChange = 100*PercentChange) %>%
#     filter(Misspec. == "Yes") %>%
#   xtable(digits = 5,
#          caption = "Simulation results over $50,000$ replications with small samples (correctly specified models)")

```
### Setting Percent Change
```{r}
X11 = mean(filter(SmallSampleResultsTable, Misspec. == "No")$PercentChange)
X12 = mean(filter(SmallSampleResultsTable, Misspec. == "Yes")$PercentChange)

X21 = mean(filter(SmallSampleResultsTable, Homo. == "Yes")$PercentChange)
X22 = mean(filter(SmallSampleResultsTable, Homo. == "No")$PercentChange)
           
X31 = mean(filter(SmallSampleResultsTable, Leverage == "No")$PercentChange)
X32 = mean(filter(SmallSampleResultsTable, Leverage == "Yes")$PercentChange)

X41 = mean(filter(SmallSampleResultsTable, K == 1)$PercentChange)
X42 = mean(filter(SmallSampleResultsTable, K == 5)$PercentChange)

SmallSettingPercentChange = matrix(c(X11,X12,X21,X22,X31,X32,X41,X42),
                                   ncol = 2,
                                   byrow = TRUE)*100
rownames(SmallSettingPercentChange) = c("Misspecification", "Heteroscedasticity", "High Leverage",  "More Covariates")
colnames(SmallSettingPercentChange) = c("Without setting", "In setting")

# SmallSettingPercentChange %>% xtable(digits = 5)
SmallSettingPercentChange
```
### Monte Carlo
```{r}
SmallSampleMCCombined = SmallSampleMonteCarloResults$CombinedTables
# SmallSampleMCCombined %>% 
#   xtable(digits = 5,
#          caption = "he Monte carlo average, variance, and confidence intervals of ˆSE_{Pop} and ˆSE_{Cond} across
# 50,000 replications.")
```


## Large Sample


### Coverage
```{r}
for(k in unique(LargeSampleResultsTable$SS)){
LargeSampleResultsTable %>%
  select(-c(Difference, Indicator)) %>%
  filter(SS == k) %>%
  xtable(digits = 5,
         caption = paste0("Complete summary of simulation with sample size ", k)) %>%
    print(include.rownames=FALSE)
  
}
```




```{r}
### Correctly Specified Models ###
# LargeSampleResultsTable %>% 
#   select(-c(Population, Conditional, Difference, Indicator, PercentChange)) %>% 
#   filter(Misspec. == "No") %>%
#   xtable(digits = 5,
#          caption = "Simulation coverage rates for 50,000 replications with Large samples (correctly specified models)")

### Misspecified Models ###
# LargeSampleResultsTable %>%
#   select(-c(Population, Conditional, Difference, Indicator, PercentChange)) %>%
#   filter(Misspec. == "Yes") %>%
#   xtable(digits = 5,
#          caption = "Simulation coverage rates for 50,000 replications with Large samples (misspecified models)")
```
### Percentage Change
```{r}
### Correctly Specified Models ###
# LargeSampleResultsTable %>%
#   select(-c(ThetaPop_VPop, ThetaPop_VCond, ThetaCond_VPop, ThetaCond_VCond, Difference, Indicator)) %>%
#   mutate(PercentChange = 100*PercentChange) %>%
#     filter(Misspec. == "No") %>%
#   xtable(digits = 5,
#          caption = "Simulation results over $50,000$ replications with Large samples (correctly specified models)")
# 
# ### Misspecified Models ###
# LargeSampleResultsTable %>%
#   select(-c(ThetaPop_VPop, ThetaPop_VCond, ThetaCond_VPop, ThetaCond_VCond, Difference, Indicator)) %>%
#   mutate(PercentChange = 100*PercentChange) %>%
#     filter(Misspec. == "Yes") %>%
#   xtable(digits = 5,
#          caption = "Simulation results over $50,000$ replications with Large samples (correctly specified models)")

```
### Setting Percent Change
```{r}
X11 = mean(filter(LargeSampleResultsTable, Misspec. == "No")$PercentChange)
X12 = mean(filter(LargeSampleResultsTable, Misspec. == "Yes")$PercentChange)

X21 = mean(filter(LargeSampleResultsTable, Homo. == "Yes")$PercentChange)
X22 = mean(filter(LargeSampleResultsTable, Homo. == "No")$PercentChange)
           
X31 = mean(filter(LargeSampleResultsTable, Leverage == "No")$PercentChange)
X32 = mean(filter(LargeSampleResultsTable, Leverage == "Yes")$PercentChange)

X41 = mean(filter(LargeSampleResultsTable, K == 1)$PercentChange)
X42 = mean(filter(LargeSampleResultsTable, K == 5)$PercentChange)

LargeSettingPercentChange = matrix(c(X11,X12,X21,X22,X31,X32,X41,X42),
                                   ncol = 2,
                                   byrow = TRUE)*100
rownames(LargeSettingPercentChange) = c("Misspecification", "Heteroscedasticity", "High Leverage",  "More Covariates")
colnames(LargeSettingPercentChange) = c("Without setting", "In setting")

# LargeSettingPercentChange %>% xtable(digits = 5)
LargeSettingPercentChange
```