---
title: "Stats 572 - Simulation Study Comparison"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Libr.
```{r}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

## Functions
```{r}
source(paste0(dir,"Code/AIZResults.R"))
source(paste0(dir,"Code/DiscrepancyFunction.R"))
source(paste0(dir,"Code/MonteCarloResults.R"))
source(paste0(dir,"Code/SimulationReformatResultsFunction.R"))
```

## Results

```{r}
file_list = list.files(path =  paste0(dir,"Results/Linear/N500_2000"), 
                        pattern = "\\.rds$", 
                        full.names = TRUE)
data_list = list()
data_list = lapply(file_list, readRDS)
rm(file_list)
# names(data_list) = paste0("Case",1:length(data_list))
```


```{r}
### Set Up ###
SettingType = "Linear"
AIZ = AIZResults(type = SettingType)
SimulationResultsList = readRDS(file = paste0(dir,"data/SimulationCases/", SettingType, "/SimulationResults.rds"))
# SimulationResultsReformatted = SimulationReformatResultsFunction(SimulationResultsList)
SimulationResultsReformatted = SimulationReformatResultsFunction(data_list)
SimSEMedianList = SimulationResultsReformatted$SimSEMedianList 
MonteCarloREsults = MonteCarloResults(SimulationResultsReformatted, 5)
RunTimeList = SimulationResultsReformatted$RunTimeList # in seconds
CoverageList = data.frame(SimulationResultsReformatted$CoverageList)
ParameterVector = SimulationResultsReformatted$ParameterVector
```

```{r}
SimSEMedianList = SimSEMedianList %>% arrange(Misspec., Homo., SS, Leverage, K)
SimSEMedianList
```


# Comparison
```{r}
DiscrepancyResults = DiscrepancyFunction(epsilon = 0.1, AIZ, SimSEMedianList, CoverageList)
Dicrepancy = DiscrepancyResults$Discrepancy
LargeDiscrepancyIndices = DiscrepancyResults$LargeDiscrepancyIndices
DiscrepancyMeans = DiscrepancyResults$MeanDiscrepancy
LargeDiscrepancyIndices
DiscrepancyMeans
```
# xtable
```{r}
### AIZ Coverage and SE Table ###
# cbind(SimSEMedianList[,c(1:5)],CoverageList,SimSEMedianList[,c(6,7,8)]) %>%
# xtable(digits = 5,
#        caption = "Simulation Results (Linear Model)")

# ### Monte Carlo Results ###
# MonteCarloREsults$MonteCarliResults_Population %>%
#   xtable(digits = 5,
#          caption = "Monte Carlo Simulation $\theta_{Cond}$ Results (Linear Model)")
# 
# MonteCarloREsults$MonteCarliResults_Conditional %>%
#   xtable(digits = 5,
#          caption = "Monte Carlo Simulation $\theta_{Pop}$ Results (Linear Model)")
```




