---
title: "Stats 572 - AN APPLICATION TO CROSS-COUNTRY GROWTH REGRESSIONS"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up
## Notes

## Libr.
```{r message=FALSE, warning=FALSE}
library(stats)
library(tidyverse)
library(StatMatch)
library(lmtest)
library(sandwich)
library(xtable)
```

## Rm. Var.
```{r}
rm(list=ls())
```

## Functions
```{r}
dir = "/Users/simondn/Documents/Stats572/"
source(paste0(dir,"Code/VHatPopFunction.R"))
source(paste0(dir,"Code/VHatCondFunction.R"))
source(paste0(dir,"Code/ReformatApplicationData.R"))
source(paste0(dir,"Code/WhichMinFunction.R"))
source(paste0(dir,"Code/AIZResults.R"))
```

# Run
## Set Up 
```{r}
AIZ = AIZResults("Application")
dat = read.csv("/Users/simondn/Documents/Stats572/data/SachsWarner/sachs.csv") %>%
  ReformatApplicationDataFunction() 
```

## Model
```{r}
VarFixed = c("gdp65","dpop","inst","tropics","land","sxp","life","life2")
VarFixed = NA
model = lm(Y ~ gdp65 + open + open*gdp65 + dpop + cgb + inst + tropics + land + sxp + life + life2, 
           data = dat)
beta_hat = as.numeric(model$coefficients)
epsilon_hat = as.numeric(model$residuals)
VCond = VHatCondFunction(dat, epsilon_hat, VarFixed = VarFixed)$RegressionSE
VPop = VHatPopFunction(dat, beta_hat)$RegressionSE
```


# Comparison
```{r}
### Mine ###
MyResults = cbind(beta_hat, VPop, VCond)
colnames(MyResults) = c("Estimates", "PopSE", "CondSE")
rownames(MyResults) = rownames(AIZ)
MyResults = data.frame(MyResults) %>% mutate(PercentChange = 100*(CondSE - PopSE)/PopSE)

### Estimate Comparison ###
EstimateComparison = data.frame(cbind(AIZ$Estimate, beta_hat, AIZ$Estimate - beta_hat)) %>% round(2)
colnames(EstimateComparison) = c("AIZ Estimate", "My Estimate", "Difference")
rownames(EstimateComparison) = rownames(AIZ)

### Population Comparison
PopulationComparison = data.frame(cbind(AIZ$POPse, VPop, AIZ$POPse - VPop)) %>% round(2)
colnames(PopulationComparison) = c("AIZ Population", "My Population", "Difference")
rownames(PopulationComparison) = rownames(AIZ)

### Conditional Comparison
ConditionalComparison = data.frame(cbind(AIZ$CONDse, VCond, AIZ$CONDse - VCond)) %>% round(2)
colnames(ConditionalComparison) = c("AIZ Conditional", "My Conditional", "Difference")
rownames(ConditionalComparison) = rownames(AIZ)

EstimateComparison
PopulationComparison
ConditionalComparison

MyResults %>% xtable(digits =3)
```

# Test
```{r}
# pb = txtProgressBar(min = 0, 
#                       max = nrow(dat)^2,
#                       style = 3,  
#                       width = 50,
#                       char = "=")
# Vx = cov(dat[,c(3,5,7,8,9,10,11,12)])
# DifferenceMatrix = numeric(83*83) %>% matrix(nrow = 83)
# for(i in 1:nrow(dat)){
#   for(j in 1:nrow(dat)){
#     setTxtProgressBar(pb, j + 83*(i-1))
#     DifferenceIteartion = as.matrix(dat[i,c(3,5,7,8,9,10,11,12)] - dat[j,c(3,5,7,8,9,10,11,12)],nrow = 1)
#     MahlanobisDistanceIteration = DifferenceIteartion %*% Vx %*% t(DifferenceIteartion)
#     DifferenceMatrix[i,j] = MahlanobisDistanceIteration
#   }
# }
```

```{r}
### Nota Bene ###
# Note that 0's in ExpandGridCombinations mean they were conditioned on
# Note that 1's in ExpandGridCombinations mean they were NOT conditioned (excluded)
 ### Set Up ###
# N = nrow(dat)
# Y = dat$Y
# X = select(dat,-c(Y,name)) %>%
#   mutate(X0 = rep(1,nrow(dat)),
#          open65 = open*gdp65) %>%
#   relocate(X0, .before = gdp65) %>%
#     as.matrix
# 
# ### Combinations ###
# ExpandGridCombinations <- expand.grid(replicate(12, c(0, 1), simplify = FALSE))
# colnames(ExpandGridCombinations) = colnames(X)
# ExpandGridCombinations$RowName = 1:nrow(ExpandGridCombinations)
# VCondList = matrix(numeric(12*nrow(ExpandGridCombinations)), ncol = 12)
# DifferenceList = matrix(numeric(12*nrow(ExpandGridCombinations)), ncol = 12)
# 
# ### Loop ###
# for (i in 1:nrow(ExpandGridCombinations)) {
# 
#   # Subset #
#   ExcludeVar <- which(ExpandGridCombinations[i, 1:12] == 1)
# 
#   # VCond Intercept #
#   VCondIteration = tryCatch(VHatCondFunctionLoop(dat, epsilon_hat, ExcludeVar)$RegressionSE, error=function(err) NA)
#   VCondIteration[c(1:4,7:10,12)] = round(VCondIteration[c(1:4,7:10,12)],2)
#   VCondIteration[c(5,6,11)] = round(VCondIteration[c(5,6,11)],2)
#   # print(VCondIteration)
#   if(any(is.na(VCondIteration))){VCondIteration = rep(NA,12)}
#   VCondList[i,] = VCondIteration
#   DifferenceList[i,] = abs(VCondIteration - AIZ[,3])
# }
# 
# ### Reformat ###
# DifferenceList = data.frame(DifferenceList)
# VCondList = data.frame(VCondList)
# DifferenceList$norm = apply(X = DifferenceList[,1:12], MARGIN = 1, FUN = function(x) norm(as.matrix(x)))
# DifferenceList$ZeroCount = rowSums(DifferenceList <.001)
# DifferenceList$RowName = 1:nrow(DifferenceList)
# VCondList$RowName = 1:nrow(VCondList)
# 
# colnames(DifferenceList) = c(colnames(X), "Norm", "ZeroCount", "RowName")
# colnames(VCondList) = c(colnames(X), "RowName")
# DifferenceList = na.omit(DifferenceList)
# VCondList = na.omit(VCondList)
# 
# ### Check ###
# for(k in c(2070,376,474)){
#   print(k)
#   # filter(DifferenceList, RowName == k) %>% print()
#   filter(ExpandGridCombinations, RowName == k) %>% print()
#   print("---")
# }
# 
# (ExpandGridCombinations %>% filter(X0 == 1,
#                                   open == 1,
#                                   cgb == 1,
#                                   open65 ==1))$RowName -> Indices
# 
# test = filter(DifferenceList, RowName %in% Indices)
```





