---
title: "Stats 572 - Simulation Study Comparison"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Libr.
```{r}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
```

## Rm. Var.
```{r}
# rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
# dir = "/Users/simondn/Downloads/Stats572-FindCoverageBug/"

```

## Functions
```{r}
source(paste0(dir,"Code/AIZResults.R"))
source(paste0(dir,"Code/DiscrepancyFunction.R"))
source(paste0(dir,"Code/MonteCarloResults.R"))
source(paste0(dir,"Code/SimulationReformatResultsFunction.R"))
```

## Results
```{r}
### AIZ Results ###
SettingType = "Linear"
AIZ = AIZResults(type = SettingType)

### My Results ###
file_list = list.files(path =  paste0(dir,"Results/Linear/N50_200"), 
                        pattern = "\\.rds$", 
                        full.names = TRUE)
SmallSampleSimulation = list()
SmallSampleSimulation = lapply(file_list, readRDS)
rm(file_list)

# SmallSampleSimulation = readRDS("/Users/simondn/Documents/Stats572/data/SimulationCases_Deprecated/Linear/SimulationResults.rds")
SmallSampleSimulation = SimulationReformatResultsFunction(SmallSampleSimulation)
SmallSampleSEMedianList = SmallSampleSimulation$SimSEMedianList 
SmallSampleMonteCarloREsults = MonteCarloResults(SmallSampleSimulation, 5)
SmallSampleRunTimeList = SmallSampleSimulation$RunTimeList # in seconds
SmallSampleCoverageList = data.frame(SmallSampleSimulation$CoverageList)
SmallSampleParameterVector = SmallSampleSimulation$ParameterVector

SmallSampleResultsTable = cbind(SmallSampleSEMedianList[,c(1:5)],
                                SmallSampleCoverageList,
                                SmallSampleSEMedianList[,c(6,7,8)]) %>%
  arrange(Misspec., Homo., SS, Leverage, K)
rownames(SmallSampleResultsTable) = paste0("Case ", 1:nrow(SmallSampleResultsTable)) 

SmallSampleResultsTable = SmallSampleResultsTable %>% mutate(Misspec. = case_when(Misspec. == 0 ~ "No",
                                                                  Misspec. == 1 ~ "Yes"),
                                             Homo. = case_when(Homo. == 0 ~ "Yes",
                                                               Homo. == 0.5 ~ "No"),
                                             Leverage = case_when(Leverage == 0 ~ "No",
                                                                  Leverage == 0.1 ~ "Yes"))
```

```{r}
# cbind(ParameterVector[17:32,], Diff = SmallSampleCoverageList$ThetaPop_VPop[17:32] - SmallSampleCoverageList$ThetaCond_VPop[17:32])
# cbind(ParameterVector[17:32,], Diff = SmallSampleCoverageList$ThetaPop_VCond[17:32] - SmallSampleCoverageList$ThetaCond_VCond[17:32])
```


# Comparison
```{r}
DiscrepancyResults = DiscrepancyFunction(epsilon = 0.1, AIZ, SmallSampleSEMedianList, SmallSampleCoverageList)
Dicrepancy = DiscrepancyResults$Discrepancy
LargeDiscrepancyIndices = DiscrepancyResults$LargeDiscrepancyIndices
DiscrepancyMeans = DiscrepancyResults$MeanDiscrepancy
LargeDiscrepancyIndices
DiscrepancyMeans
```

# xtable
```{r}
### AIZ Coverage and SE Table ###
# cbind(SimSEMedianList[,c(1:5)],CoverageList,SimSEMedianList[,c(6,7,8)]) %>%
# xtable(digits = 5,
#        caption = "Simulation Results (Linear Model)")

# ### Monte Carlo Results ###
# MonteCarloREsults$MonteCarliResults_Population %>%
#   xtable(digits = 5,
#          caption = "Monte Carlo Simulation $\theta_{Cond}$ Results (Linear Model)")
# 
# MonteCarloREsults$MonteCarliResults_Conditional %>%
#   xtable(digits = 5,
#          caption = "Monte Carlo Simulation $\theta_{Pop}$ Results (Linear Model)")
```




