---
title: "Stats 572 - Run Simulation Study 1"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up
## Notes

## Libr.
```{r message=FALSE, warning=FALSE}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
library(mixtools)
library(distr)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

# Functions
```{r}
source(paste0(dir,"Code/AIZResults.R"))
source(paste0(dir,"Code/ConfidenceIntervalFunction.R"))
source(paste0(dir,"Code/OneIterationFunction.R"))
source(paste0(dir,"Code/SimDataLinear.R"))
source(paste0(dir,"Code/SimDataLogistic.R"))
source(paste0(dir,"Code/SimulationFunction.R"))
source(paste0(dir,"Code/SimulationReformatResultsFunction.R"))
source(paste0(dir,"Code/ThetaCondFunction.R"))
source(paste0(dir,"Code/ThetaPopFunction.R"))
source(paste0(dir,"Code/VHatCondFunction.R"))
source(paste0(dir,"Code/VHatPopFunction.R"))
source(paste0(dir,"Code/WhichMinFunction.R"))
```

# Set Up
```{r}
AIZ = AIZResults("Logistic")
### Set Up ###
set.seed(1)
TypeSetting = "Logistic"
ParameterVector = cbind(MisspecVec = c(rep(0,16),rep(1,16)),                        # Delta: Misspecification Rate
                        HomoskedVec = rep(c(rep(0,8), rep(0.5,8)),2),                # Gamma: Heteroskedasticity Rate
                        SizeVec = rep(c(rep(50,4), rep(200,4)),4),                   # N: Observations
                        LeverageVec = rep(c(0,0,0.1,0.1),8),                         # rho: Mixture Leverage
                        KVec = rep(c(1,5),16)                                        # K: Parameters
                        ) %>% data.frame
VarFixed = NA
```

# Simulation

### SimDataLogistic
```{r}
### Set Up ###
NSim = 100
ResultsList = matrix(numeric(nrow(ParameterVector)* 11), ncol =11)
colnames(ResultsList) = c("delta", "gamma", "N", "rho", "K", "VPop", "VCond", 
                          "CoverageThetaPopVPop",
                          "CoverageThetaPopVCond",
                          "CoverageThetaCondVPop",
                          "CoverageThetaCondVCond")
```

```{r}
# for(SimCase in 1:nrow(ParameterVector)){
for(SimCase in 1:8){
  ### Set Up ###
  ThetaPopList = numeric(NSim)
  ThetaCondList = numeric(NSim)
  VPopSEList = numeric(NSim)
  VCondSEList = numeric(NSim)
  CoverageResultsList = numeric(4*NSim) %>% matrix(ncol = 4)
  
  ### Progress Bar ####
  print(paste0("Case: ",SimCase))
  pb = txtProgressBar(min = 0, 
                        max = NSim,
                        style = 3,  
                        width = 50,
                        char = "=")
  
  ### Parameters ###
  delta = ParameterVector$MisspecVec[SimCase]  
  gamma =  ParameterVector$HomoskedVec[SimCase]  
  N = ParameterVector$SizeVec[SimCase]            
  rho =  ParameterVector$LeverageVec[SimCase]     
  K = ParameterVector$KVec[SimCase] 
  
  for(i in 1:NSim){
    # print(i)
    setTxtProgressBar(pb, i)
    
    ### Data Generating Process 
    SimData = SimDataLogistic(N, rho, K, delta, gamma)
    dat = SimData$dat
    mu = SimData$mu
    
    ### Model ###
    model <- glm(Y ~ ., data = dat, family = binomial(link = "logit"))
    beta_hat = as.numeric(model$coefficients) 
    epsilon_hat = as.numeric(model$residuals)
    
    ### Theta Pop ###
    ThetaPopList[i] = ThetaPopFunction(rho_i = rho, 
                              N_i = N,
                              K_i = K, 
                              delta_i = delta, 
                              gamma_i = gamma, 
                              TypeSetting = TypeSetting)
    ThetaCondList[i] = ThetaCondFunction(dat, mu, TypeSetting = TypeSetting)
    
    ### Standard Errors ###
    VPopSEList[i] = sqrt(diag(vcovHC(model, type = "HC0")))[2]
    VCondSEList[i] = VHatCondFunction(dat, epsilon_hat, VarFixed = NA)$RegressionSE[2]
    
     # Confidence Interval #
    CoverageResultsList[i,] = ConfidenceIntervalFunction(ThetaHat = beta_hat[2],
                                                 ThetaCond = ThetaCondList[i],
                                                 ThetaPop = ThetaPopList[i],
                                                 SEPop = VPopSEList[i],
                                                 SECond = VCondSEList[i],
                                                 alpha = .05)
  }
  
  ResultsList[SimCase, ] = c(delta=delta, 
                             gamma=gamma, 
                             N=N, 
                             rho=rho, 
                             K = K, 
                             VPop = mean(VPopSEList), 
                             VCond = mean(VCondSEList),
                             CoverageThetaPopVPop =  mean(CoverageResultsList[,1]),
                             CoverageThetaPopVCond =  mean(CoverageResultsList[,2]),
                             CoverageThetaCondVPop =  mean(CoverageResultsList[,3]),
                             CoverageThetaCondVCond =  mean(CoverageResultsList[,4])
                             )

}
ResultsList = data.frame(ResultsList)

```


```{r}
VPopDifference = cbind(ParameterVector, AIZ$MedianSEPop - ResultsList$VPop)
VCondDifference = cbind(ParameterVector, AIZ$MedianSECond - ResultsList$VCond)
ResultsList$PercentChange = (ResultsList$VCond-ResultsList$VPop)/ResultsList$VPop
AIZ$PercentChange = (AIZ$MedianSECond-AIZ$MedianSEPop)/AIZ$MedianSEPop

TPopVPopDifference = AIZ[,6] - ResultsList[,8]
TPopVCondDifference = AIZ[,7] - ResultsList[,9]
TCondVPopDifference = AIZ[,8] - ResultsList[,10]
TCondVCondDifference = AIZ[,9] - ResultsList[,11]

colnames(VPopDifference) = c("delta", "gamma", "N", "rho", "K", "Difference")
colnames(VCondDifference) = c("delta", "gamma", "N", "rho", "K", "Difference")

DifferenceInDifference = (AIZ$MedianSEPop - AIZ$MedianSECond) - (VPopDifference$Difference - VCondDifference$Difference)
DifferenceInPercentChange = AIZ$PercentChange - ResultsList$PercentChange


print(length(DifferenceInDifference))

DifferenceTable = cbind(VPopDifference, 
                        VCondDifference$Difference, 
                        DifferenceInDifference,
                        DifferenceInPercentChange,
                        TPopVPopDifference,
                        TPopVCondDifference,
                        TCondVPopDifference,
                        TCondVCondDifference)

colnames(DifferenceTable) = c("delta", "gamma", "N", "rho", "K", 
                              "VPopDiff", 
                              "VCondDiff",
                              "DifferenceInDifferences",
                              "DifferencePercentChange",
                              "TPopVPopDifference",
                              "TPopVCondDifference",
                              "TCondVPopDifference",
                              "TCondVCondDifference")

DifferenceTable
```


