---
title: "Stats 572 - Simulation Study Comparison"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Libr.
```{r}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
TypeSetting  = "Linear"
```


```{r}
N50_2000FTP = readRDS(paste0(dir,"data/",TypeSetting,"/EstimatedThetaPop.rds"))
```

## Functions
```{r}
FileList = list.files(path =  paste0(dir,"data/",TypeSetting,"/EstimatedThetaPop"), 
                      pattern = "\\.csv$", 
                      full.names = TRUE)
FileList = lapply(FileList, read.csv)

ThetaPopList = matrix(nrow = length(FileList), ncol = 6)
for(i in 1:length(FileList)){
  ThetaPopList[i,] = FileList[[i]]$x
}

ThetaPopList = data.frame(ThetaPopList)
colnames(ThetaPopList) = c("delta","rho","N","gamma","K","ThetaPop")
ThetaPopList = ThetaPopList %>% mutate(ThetaPop = round(ThetaPop,2))

saveRDS(AllThetaPopList,paste0(dir,"data/",TypeSetting,"/EstimatedThetaPop/EstimatedThetaPop.rds"))
```

```{r}
table(NewThetaPopList$N)
table(N50_2000FTP$N)

AllThetaPopList = rbind(N50_2000FTP, NewThetaPopList)
```



