---
title: "Stats 572 - Run Simulation Study 1"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: assets/styles.css
---

# Set Up
## Notes
- Did I do the Mahlahnobis distance correctly

## Libr.
```{r message=FALSE, warning=FALSE}
library(stats)
library(tidyverse)
library(StatMatch)
library(xtable)
library(lmtest)
library(sandwich)
library(mixtools)
library(distr)
```

## Rm. Var.
```{r}
rm(list=ls())
dir = "/Users/simondn/Documents/Stats572/"
```

# Functions
```{r}
source(paste0(dir,"Code/functions/AIZResults.R"))
source(paste0(dir,"Code/functions/ConfidenceIntervalFunction.R"))
source(paste0(dir,"Code/functions/OneIterationFunction.R"))
source(paste0(dir,"Code/functions/SimDataLinear.R"))
source(paste0(dir,"Code/functions/SimDataLogistic.R"))
source(paste0(dir,"Code/functions/SimulationFunction.R"))
source(paste0(dir,"Code/functions/SimulationReformatResultsFunction.R"))
source(paste0(dir,"Code/functions/ThetaCondFunction.R"))
source(paste0(dir,"Code/functions/ThetaPopFunction.R"))
source(paste0(dir,"Code/functions/VHatCondFunction.R"))
source(paste0(dir,"Code/functions/VHatPopFunction.R"))
source(paste0(dir,"Code/functions/WhichMinFunction.R"))
```

# Set Up
```{r}
### Set Up ###
set.seed(420)
TypeSetting = "Linear"
ParameterVector = cbind(MisspecVec = c(rep(0,16),rep(1,16)),                        # Delta: Misspecification Rate
                        HomoskedVec = rep(c(rep(0,8), rep(0.5,8)),2),                # Gamma: Heteroskedasticity Rate
                        SizeVec = rep(c(rep(50,4), rep(200,4)),4),                   # N: Observations
                        LeverageVec = rep(c(0,0,0.1,0.1),8),                         # rho: Mixture Leverage
                        KVec = rep(c(1,5),16)                                        # K: Parameters
                        ) %>% data.frame
```

# Simulation
```{r}
### Run Simulation ###
NSim = 10
SimulationResultsList = list(length = nrow(ParameterVector))
for(i in 1:nrow(ParameterVector)){
  print(paste0("Case ",i))
SimulationResultsList[[i]] = SimulationFunction(NSim = NSim, 
                                                ParameterVector = ParameterVector, 
                                                SimulationCase = i, 
                                                VarFixed = NA,
                                                TypeSetting = TypeSetting)
  # write.csv(SimulationResultsList[[i]]$SimulationSEResults, 
            # file = paste0(dir, "data/SimulationCases/",TypeSetting,"/StandardErrors/Case",i,".csv"))
  # write.csv(SimulationResultsList[[i]]$SimCoverageFrequency, 
            # file = paste0(dir, "data/SimulationCases/",TypeSetting,"/Coverage/Case",i,".csv"))
}
names(SimulationResultsList) = paste0("Case",1:nrow(ParameterVector))
# saveRDS(SimulationResultsList, file = paste0(dir,"data/SimulationCases/",TypeSetting,"/SimulationResults.rds"))
```




